language: ruby
rvm:
  - 2.2.2
bundler_args: --without production
script:
  - bin/check
  - bundle exec rspec
addons:
  code_climate:
    repo_token: <%= ENV['CODECLIMATE_REPO_TOKEN'] %>
  postgresql: '9.3'
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp config/database.travis.yml config/database.yml
