language: ruby

rvm:
  - 2.2.3

cache: bundler

addons:
  code_climate:
    repo_token: 1e68b6097ac93461d2d48687220ebb7dbd8b37c7da3e884cd15f5f2cba987334
  postgresql: '9.4'

bundler_args: --without production

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - cp config/database.travis.yml config/database.yml
    - cp config/application.travis.yml config/application.yml
    - cp spec/code_climate.ci.rb spec/code_climate.rb
    - gem install scss-lint
    - npm install -g coffeelint

script:
  - bundle exec rspec
  - bin/shcheck
