postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: ''

development:
  <<: *postgres
  database: simple_job_runner_development

test:
  <<: *postgres
  database: simple_job_runner_test

production:
  <<: *postgres
  database: simple_job_runner_production
