postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *postgres
  database: travis_ci_test

test:
  <<: *postgres
  database: travis_ci_test

production:
  <<: *postgres
  database: travis_ci_test
